#!/usr/bin/env python3
"""plot_equilibria_payoffs.py

Read deviation_payoffs.csv (generated by equilibrium_deviation_payoffs.py)
and draw a summary plot identical in style to
analysis/compare_pooled_bootstrap_all_lines_by_hp.png but for *any*
set of HP values present in the CSV.

Usage
-----
    python scripts/plot_equilibria_payoffs.py                   # default file
    python scripts/plot_equilibria_payoffs.py --csv myfile.csv  # custom csv

The script outputs two PNGs:
    payoffs_mobi.png   – MOBI role
    payoffs_zi.png     – ZI   role
Each shows the equilibrium value V_r(x̂) together with deviation
payoffs (MELO, CDA) across HP.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# canonical label mapping used by original figure
LABEL_MAP = {
    "V_role": "Equilibrium Value",
    "MELO": "Dev: MELO",
    "CDA": "Dev: CDA",
}

COLOUR_MAP = {
    "Equilibrium Value": "black",
    "Dev: MELO": "royalblue",
    "Dev: CDA": "darkorange",
}

MARKER_MAP = {
    "Equilibrium Value": "s",
    "Dev: MELO": "o",
    "Dev: CDA": "o",
}


def main() -> None:
    ap = argparse.ArgumentParser(description="Plot deviation payoffs by HP from CSV")
    ap.add_argument("--csv", type=str, default="deviation_payoffs.csv", help="input CSV file")
    args = ap.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.exists():
        raise FileNotFoundError(csv_path)

    df = pd.read_csv(csv_path)
    if df.empty:
        raise RuntimeError("CSV is empty – nothing to plot")

    # Ensure we have an equilibrium identifier column.
    if "EqID" not in df.columns:
        # infer EqID by counting how many V_role rows we've seen per HP,Role
        df = df.copy()
        df["EqID"] = df.groupby(["HP", "Role", "Strategy"]).cumcount()
        # All non-V_role rows should inherit the same EqID as their block
        # We'll forward-fill within HP,Role groups
        ff = df.sort_values(["HP", "Role", "EqID", "Strategy"]).copy()
        ff["EqID"] = ff.groupby(["HP", "Role"]).EqID.ffill().astype(int)
        df = ff

    for role in sorted(df["Role"].unique()):
        sub_role = df[df["Role"] == role].copy()

        # decode strategy names into compact labels
        def _pretty(s):
            if s == "V_role":
                return "Equilibrium Value"
            if "_0_100" in s:
                return "Dev: MELO"
            if "_100_0" in s:
                return "Dev: CDA"
            return s

        sub_role["Pretty"] = sub_role["Strategy"].map(_pretty)

        hp_sorted = sorted(sub_role["HP"].unique())
        fig, ax = plt.subplots(figsize=(10,4))

        # loop over equilibria
        eq_ids = sorted(sub_role["EqID"].unique())
        colours_cycle = plt.cm.tab10.colors
        for eq_idx, eq_id in enumerate(eq_ids):
            sub_eq = sub_role[sub_role["EqID"] == eq_id]
            for pretty, grp in sub_eq.groupby("Pretty"):
                grp = grp.sort_values("HP")
                x = grp["HP"].to_numpy()
                y = grp["Payoff"].to_numpy()

                base_color = COLOUR_MAP.get(pretty, colours_cycle[eq_idx % len(colours_cycle)])
                # shift colour slightly per equilibrium to distinguish lines
                color = base_color if len(eq_ids)==1 else colours_cycle[(eq_idx+ (0 if pretty=='Equilibrium Value' else 5)) % len(colours_cycle)]
                label_name = pretty if len(eq_ids)==1 else f"{pretty} (eq{eq_idx+1})"

                ax.plot(
                    x, y,
                    label=label_name,
                    color=color,
                    marker=MARKER_MAP.get(pretty, "o"),
                    linewidth=2 if pretty == "Equilibrium Value" else 1.5,
                    alpha=0.9 if pretty=="Equilibrium Value" else 0.7,
                )

        ax.set_xticks(hp_sorted)
        ax.set_xticklabels([str(int(h)) for h in hp_sorted], rotation=45, ha="right")
        ax.set_xlabel("Holding Period")
        ax.set_ylabel("Payoff")
        ax.set_title(f"{role} – Deviations vs V_r(x̂)")
        ax.grid(alpha=.3)
        ax.legend(frameon=False)
        plt.tight_layout()
        out_png = Path(f"payoffs_{role.lower()}.png")
        plt.savefig(out_png, dpi=200)
        plt.close()
        print("Saved", out_png)


if __name__ == "__main__":
    main()
